### ISSUE TITLE
False auth

### ISSUE THREAD

**Issue by ArielS1** [J-Priebe/react-native-facebook-firebase#2]
I followed all readme instructions and got the app running
The problem is that on the first screen i get a "continue with facebook" button at the first time without having logged.
And when i click it it says an error that im not logged in.

I should get a log in with facebook instead of it.

I suspected it happened because  i had anonymous login configuration enabled in firebase, but i disabled it and it still happens

**Comment by J-Priebe** [comment]
Can you include errors/debug output and screenshots?  
What happens when you exit and reopen the app? Does it still show the incorrect screen?

**Comment by ArielS1** [comment]
There are no errors and no debug msgs, and yes the problem repeats even that I tried to change the emulator.

I'm checking a new lead on the cause:
I may have to generate some hash key of the machine that compiles the APK and configure it in my fb app's console and also supply the package and activity name

Is that something you had to do?

I'll update later about the outcome

**Comment by J-Priebe** [comment]
You should only have to modify `strings.xml` and `AndroidManifest.xml` as described in the README. Examples are in the `ANDROID_TEMPLATE_FILES` folder.

**Comment by J-Priebe** [comment]
ALSO - you must enable Facebook sign-in from your firebase console and provide your Facebook App ID and Secret, and add a redirect URI from the Facebook console:
https://firebase.google.com/docs/auth/web/facebook-login

README has been fixed to reflect this!

**Comment by ArielS1** [comment]
Hi,

I already did before what you have suggested...

Anyway i managed to fix the problem by adding an Android platform to my facebook app.

It's an ugly process and i got hours of troubleshooting it.

I read somewhere that if you don't do it then the auth MAY not work properly on debug or maybe at some point later at the production when it's at the appstore, i got the problems now...

I found a good guide that helped me do it:
http://blog.mauriziobonani.com/integrate-fbsdk-in-react-native/

at the sectio of "Tell us about your Android project"

I had troubles with openssl and this guide helped me fix them:
https://www.tbs-certificates.co.uk/FAQ/en/openssl-windows.html

The good news is that the login is working.
the bad news is that after few seconds i see the home screen i get a red error:
"null is not an object (evaluating 'action.profileData.bio')

I'm not going to try to find how to fix that, because i'm not gonna use that feature.
maybe i had to push it before to my fb db, i don't know.

Thanks for the support and i hope this would help slmebody that gets a similar problem

**Comment by J-Priebe** [comment]
`bio` is not part of facebook authentication, you need to create a `users` table in your firebase app. The reference to the table is in `firebase.js`:
`const profileRef = firebaseApp.database().ref().child('users').child(currentUser.uid)`

I'm glad you got it working, and thank you for drawing these issues to my attention - I clearly need to improve my README :)
